version: '3.8'

services:
  jupyter:
    build: .
    container_name: jupyter_notebook
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes